"""
Dataset generator v3 — uses fully LLM-generated realistic tickets.

Instead of templates or paraphrases, this uses the 6K+ unique tickets
generated by Claude Haiku from OpenAI's help center taxonomy.
"""

import json
import random
from dataclasses import dataclass, asdict
from pathlib import Path

random.seed(42)

DATA_DIR = Path(__file__).parent.parent.parent / "app" / "public" / "data"

CUSTOMER_TIERS = ["free", "plus", "pro", "go", "enterprise", "api_only"]
TIER_WEIGHTS = [0.30, 0.25, 0.10, 0.10, 0.10, 0.15]

URGENCY_KEYWORDS_HIGH = [
    "urgent", "asap", "immediately", "critical", "blocked", "production",
    "hacked", "leaked", "unauthorized", "can't access", "locked out",
    "charged", "lost", "disappeared", "compromised",
]
URGENCY_KEYWORDS_LOW = [
    "how do i", "how to", "what is", "wondering", "question about",
    "curious", "difference between", "best practice",
]


@dataclass
class SupportTicket:
    id: int
    text: str
    category: str
    secondary_category: str | None
    customer_tier: str
    account_age_days: int
    previous_tickets: int
    is_ambiguous: bool
    urgency: str


def infer_urgency(text: str) -> str:
    """Infer urgency from ticket text content."""
    text_lower = text.lower()
    for kw in URGENCY_KEYWORDS_HIGH:
        if kw in text_lower:
            return "high"
    for kw in URGENCY_KEYWORDS_LOW:
        if kw in text_lower:
            return "low"
    return "medium"


def load_realistic_tickets():
    """Load the LLM-generated realistic tickets."""
    path = DATA_DIR / "realistic_tickets.json"
    with open(path) as f:
        tickets = json.load(f)

    by_category = {}
    for t in tickets:
        cat = t["category"]
        if cat not in by_category:
            by_category[cat] = []
        by_category[cat].append(t["text"])

    return by_category


def generate_dataset(n: int = 100_000) -> list[dict]:
    by_category = load_realistic_tickets()
    total_tickets = sum(len(v) for v in by_category.values())
    print(f"Loaded {total_tickets} realistic tickets across {len(by_category)} categories")

    # Category weights
    category_weights = {
        "billing": 0.16, "account_access": 0.14, "account_management": 0.08,
        "api_errors": 0.12, "api_usage": 0.08, "chatgpt_product": 0.15,
        "chatgpt_apps": 0.08, "enterprise": 0.06, "gpts": 0.05,
        "newer_products": 0.04, "privacy_policy": 0.03, "security": 0.01,
    }

    categories = list(category_weights.keys())
    weights = [category_weights[c] for c in categories]

    tickets = []
    for i in range(n):
        category = random.choices(categories, weights=weights, k=1)[0]
        text = random.choice(by_category[category])

        urgency = infer_urgency(text)

        customer_tier = random.choices(CUSTOMER_TIERS, weights=TIER_WEIGHTS, k=1)[0]
        account_age_days = int(random.gammavariate(2, 180))
        previous_tickets = int(random.expovariate(0.5))

        ticket = SupportTicket(
            id=i + 1,
            text=text,
            category=category,
            secondary_category=None,
            customer_tier=customer_tier,
            account_age_days=min(account_age_days, 1500),
            previous_tickets=min(previous_tickets, 20),
            is_ambiguous=False,
            urgency=urgency,
        )
        tickets.append(asdict(ticket))

    return tickets


def main():
    n = 100_000
    print(f"Generating {n:,} tickets from realistic LLM-generated text...")
    tickets = generate_dataset(n)

    # Stats
    from collections import Counter
    cats = Counter(t["category"] for t in tickets)
    urgencies = Counter(t["urgency"] for t in tickets)
    unique = len(set(t["text"] for t in tickets))

    print(f"\nCategory distribution:")
    for cat, count in cats.most_common():
        print(f"  {cat:25s} {count:6d}  ({count/len(tickets)*100:.1f}%)")

    print(f"\nUrgency distribution:")
    for urg, count in urgencies.most_common():
        print(f"  {urg:10s} {count:6d}  ({count/len(tickets)*100:.1f}%)")

    print(f"\nUnique texts: {unique:,} / {len(tickets):,} ({unique/len(tickets)*100:.1f}%)")

    # Save
    with open(DATA_DIR / "tickets.json", "w") as f:
        json.dump(tickets, f)
    size_mb = (DATA_DIR / "tickets.json").stat().st_size / 1024 / 1024
    print(f"Exported to tickets.json ({size_mb:.1f} MB)")

    sample = random.sample(tickets, 1000)
    with open(DATA_DIR / "tickets_sample.json", "w") as f:
        json.dump(sample, f, indent=2)

    stats = {}
    for cat, count in cats.most_common():
        stats[cat] = {"count": count, "percentage": round(count/len(tickets)*100, 1)}
    with open(DATA_DIR / "category_stats.json", "w") as f:
        json.dump(stats, f, indent=2)

    print("Done!")


if __name__ == "__main__":
    main()
