"""
Synthetic support ticket generator v2 — uses LLM-paraphrased templates.

Instead of category-specific keyword templates, this version uses
paraphrased variations generated by Claude Haiku, creating tickets
that require semantic understanding to classify correctly.
"""

import json
import random
from dataclasses import dataclass, asdict
from pathlib import Path

random.seed(42)

DATA_DIR = Path(__file__).parent.parent.parent / "app" / "public" / "data"

# --- Load paraphrased templates ---

def load_paraphrased_templates():
    """Load both normal and hard LLM-paraphrased templates."""
    # Normal paraphrases
    path = DATA_DIR / "paraphrased_templates.json"
    with open(path) as f:
        normal = json.load(f)

    # Hard paraphrases (deliberately ambiguous)
    hard_path = DATA_DIR / "hard_paraphrases.json"
    hard = []
    if hard_path.exists():
        with open(hard_path) as f:
            hard = json.load(f)

    # Organize by category — mix normal and hard
    by_category = {}
    for t in normal:
        cat = t["category"]
        urgency = t["urgency"]
        if cat not in by_category:
            by_category[cat] = {"normal": [], "hard": []}
        for p in t["paraphrases"]:
            by_category[cat]["normal"].append((p, urgency))

    for t in hard:
        cat = t["category"]
        urgency = t["urgency"]
        if cat not in by_category:
            by_category[cat] = {"normal": [], "hard": []}
        for p in t.get("hard_paraphrases", []):
            by_category[cat]["hard"].append((p, urgency))

    normal_count = sum(len(v["normal"]) for v in by_category.values())
    hard_count = sum(len(v["hard"]) for v in by_category.values())
    print(f"  Normal paraphrases: {normal_count}")
    print(f"  Hard paraphrases: {hard_count}")

    return by_category


# --- Category weights ---

CATEGORY_WEIGHTS = {
    "billing": 0.16,
    "account_access": 0.14,
    "account_management": 0.08,
    "api_errors": 0.12,
    "api_usage": 0.08,
    "chatgpt_product": 0.15,
    "chatgpt_apps": 0.08,
    "enterprise": 0.06,
    "gpts": 0.05,
    "newer_products": 0.04,
    "privacy_policy": 0.03,
    "security": 0.01,
}

# --- Metadata ---

CUSTOMER_TIERS = ["free", "plus", "pro", "go", "enterprise", "api_only"]
TIER_WEIGHTS = [0.30, 0.25, 0.10, 0.10, 0.10, 0.15]

# --- Ambiguous templates (multi-intent) ---

AMBIGUOUS_TEMPLATES = [
    {"texts": [
        "I noticed money taken from my account and at the same time my developer access stopped working",
        "Got charged for something I didn't buy and now my integration is broken too",
        "Two problems: unexpected charge on my card and my programmatic access is failing",
    ], "category": "billing", "secondary_category": "api_errors"},
    {"texts": [
        "I can't get into my account and when I finally did there were charges I didn't recognize",
        "Locked out of everything and now I see payments I never authorized",
        "Access issues combined with suspicious transactions on my account",
    ], "category": "account_access", "secondary_category": "billing"},
    {"texts": [
        "The mobile app keeps closing unexpectedly and all my previous conversations disappeared",
        "App crashes constantly and I've lost my entire conversation history",
        "Phone app is unusable and my saved chats are gone",
    ], "category": "chatgpt_apps", "secondary_category": "chatgpt_product"},
    {"texts": [
        "Our company login system broke and now nobody on the team can use their custom assistants",
        "Single sign-on failure is preventing our entire organization from accessing their tools",
        "Corporate authentication is down and it's blocking access to our team's custom setups",
    ], "category": "enterprise", "secondary_category": "gpts"},
    {"texts": [
        "My requests keep getting throttled and I think I'm being billed for the ones that fail",
        "Getting rejected responses but the usage counter still goes up and I'm paying for it",
        "System keeps rejecting my calls but still counting them toward my bill",
    ], "category": "api_errors", "secondary_category": "billing"},
    {"texts": [
        "I want my information removed from the system and I also need to download everything first",
        "Need to export all my data before requesting complete deletion of my information",
        "Please help me save my data and then remove my entire presence from the platform",
    ], "category": "privacy_policy", "secondary_category": "account_management"},
    {"texts": [
        "My custom assistant's external connection keeps returning errors",
        "The API integration I set up for my bot keeps failing with server errors",
        "Built a custom tool but the external service calls keep timing out",
    ], "category": "gpts", "secondary_category": "api_errors"},
    {"texts": [
        "Video generation failed but credits were still deducted from my account",
        "The creative tool didn't produce anything but I was still charged for the attempt",
        "Nothing was generated but my usage balance went down anyway",
    ], "category": "newer_products", "secondary_category": "billing"},
    {"texts": [
        "Changed my credentials and now the phone app refuses to let me back in",
        "Updated my security settings and got locked out of the mobile version",
        "Can't access the app on my phone after modifying my account login details",
    ], "category": "account_access", "secondary_category": "chatgpt_apps"},
    {"texts": [
        "The AI keeps remembering things I explicitly asked it to forget and I'm worried about my privacy",
        "System retains information I deleted and I have concerns about data handling",
        "Memory feature isn't respecting my deletion requests which raises data protection issues",
    ], "category": "chatgpt_product", "secondary_category": "privacy_policy"},
    {"texts": [
        "My credentials were exposed and someone ran up a huge bill on my account",
        "Security breach led to unauthorized usage and I now have charges I didn't make",
        "Someone got access to my developer keys and I'm seeing charges from their usage",
    ], "category": "security", "secondary_category": "billing"},
    {"texts": [
        "I want my money back AND I want every trace of my information removed from your systems",
        "Requesting a financial reversal along with complete data deletion",
        "Need both a billing adjustment and full account data purge",
    ], "category": "billing", "secondary_category": "privacy_policy"},
    {"texts": [
        "My account was compromised, they changed all my details, and there are charges from them",
        "Someone took over my account, modified my credentials, and made purchases I didn't authorize",
        "Account hijacking — intruder changed my info and ran up charges",
    ], "category": "account_access", "secondary_category": "security"},
]

CONTEXT_SUFFIXES = [
    " Thanks in advance.",
    " Please help.",
    " Any help would be appreciated.",
    " Let me know if you need more details.",
    " Thanks!",
    " Please advise.",
    "",
    "",
    "",
    "",
    "",
    "",
]

# --- Cross-category noise: generic phrases that blur category boundaries ---
# These get appended to tickets to add red-herring signals from other categories

CROSS_CATEGORY_NOISE = [
    # Billing-flavored noise (appended to non-billing tickets)
    "I'm also confused about a charge on my account.",
    "I noticed my billing looks different than expected.",
    "This is affecting my subscription.",
    "I'm paying for this service and it should work.",
    "My payment method is on file.",
    # Access-flavored noise
    "I had to log in multiple times to even get here.",
    "I've been having trouble accessing things recently.",
    "This happened right after I changed my password.",
    "I can barely get into my account as it is.",
    # API-flavored noise
    "I'm also seeing errors in my API dashboard.",
    "My integration has been flaky lately too.",
    "This might be related to the API issues I've been having.",
    "I use this through the API as well.",
    # Product-flavored noise
    "ChatGPT has been acting weird for me in general.",
    "The whole experience has been buggy lately.",
    "Other features seem to be affected too.",
    "This started after the latest update.",
    # Enterprise-flavored noise
    "Several people on my team are seeing this.",
    "Our organization relies on this for daily work.",
    "This is affecting our entire workspace.",
    "My admin is also looking into this.",
    # Generic noise
    "I've been going back and forth on this for a while.",
    "I tried everything I can think of.",
    "Nothing seems to work.",
    "I'm not sure if this is the right place to ask.",
    "I've searched the help center but couldn't find an answer.",
    "A friend suggested I reach out to support.",
    "I've seen other people complaining about this online.",
]

# --- Generic openers that obscure the real category ---
GENERIC_OPENERS = [
    "I have a problem. ",
    "Something isn't working right. ",
    "I need help with my account. ",
    "I'm having an issue. ",
    "This has been going on for a while now. ",
    "I'm not sure what's happening but ",
    "Can someone help me? ",
    "I'm frustrated because ",
    "I've tried fixing this myself but ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
]

URGENT_PREFIXES = [
    "URGENT: ",
    "This is extremely frustrating. ",
    "I've been waiting for days with no response. ",
    "This is blocking my production system. ",
    "I need immediate assistance. ",
    "This is a critical issue. ",
]

CASUAL_PREFIXES = [
    "Quick question: ",
    "Hi, ",
    "Hello, ",
    "",
    "",
    "",
]


@dataclass
class SupportTicket:
    id: int
    text: str
    category: str
    secondary_category: str | None
    customer_tier: str
    account_age_days: int
    previous_tickets: int
    is_ambiguous: bool
    urgency: str


def generate_ticket(ticket_id: int, templates_by_category: dict, force_ambiguous: bool = False) -> SupportTicket:
    """Generate a single ticket using paraphrased templates."""
    is_ambiguous = force_ambiguous or random.random() < 0.10

    if is_ambiguous:
        ambig = random.choice(AMBIGUOUS_TEMPLATES)
        text = random.choice(ambig["texts"])
        category = ambig["category"]
        secondary_category = ambig["secondary_category"]
        urgency = random.choice(["medium", "high"])
    else:
        categories = list(CATEGORY_WEIGHTS.keys())
        weights = [CATEGORY_WEIGHTS[c] for c in categories]
        category = random.choices(categories, weights=weights, k=1)[0]

        cat_data = templates_by_category.get(category, {"normal": [], "hard": []})
        # 70% of non-ambiguous tickets use hard paraphrases (if available)
        if cat_data["hard"] and random.random() < 0.70:
            text, urgency = random.choice(cat_data["hard"])
        elif cat_data["normal"]:
            text, urgency = random.choice(cat_data["normal"])
        else:
            text = f"I have an issue with {category}"
            urgency = "medium"

        secondary_category = None

    # Generic opener (25% of tickets) — obscures category signal
    if random.random() < 0.25:
        text = random.choice(GENERIC_OPENERS) + text[0].lower() + text[1:]

    # Cross-category noise (30% of tickets) — adds red-herring signals
    if random.random() < 0.30:
        text += " " + random.choice(CROSS_CATEGORY_NOISE)

    # Context suffix (20% of tickets)
    if random.random() < 0.20:
        text += random.choice(CONTEXT_SUFFIXES)

    # Tone prefix based on urgency
    if urgency == "high" and random.random() < 0.35:
        text = random.choice(URGENT_PREFIXES) + text
    elif urgency == "low" and random.random() < 0.20:
        text = random.choice(CASUAL_PREFIXES) + text

    # Metadata
    customer_tier = random.choices(CUSTOMER_TIERS, weights=TIER_WEIGHTS, k=1)[0]
    account_age_days = int(random.gammavariate(2, 180))
    previous_tickets = int(random.expovariate(0.5))

    return SupportTicket(
        id=ticket_id,
        text=text.strip(),
        category=category,
        secondary_category=secondary_category,
        customer_tier=customer_tier,
        account_age_days=min(account_age_days, 1500),
        previous_tickets=min(previous_tickets, 20),
        is_ambiguous=is_ambiguous,
        urgency=urgency,
    )


def generate_dataset(n: int = 100_000) -> list[dict]:
    templates = load_paraphrased_templates()

    total_normal = sum(len(v["normal"]) for v in templates.values())
    total_hard = sum(len(v["hard"]) for v in templates.values())
    print(f"Loaded {total_normal + total_hard} templates ({total_normal} normal + {total_hard} hard) across {len(templates)} categories")

    tickets = []
    for i in range(n):
        ticket = generate_ticket(i + 1, templates)
        tickets.append(asdict(ticket))
    return tickets


def get_category_stats(tickets):
    from collections import Counter
    counts = Counter(t["category"] for t in tickets)
    total = len(tickets)
    stats = {}
    for cat, count in counts.most_common():
        stats[cat] = {
            "count": count,
            "percentage": round(count / total * 100, 1),
        }
    return stats


def main():
    n = 100_000
    print(f"Generating {n:,} tickets with paraphrased templates...")
    tickets = generate_dataset(n)

    stats = get_category_stats(tickets)
    print("\nCategory distribution:")
    for cat, info in stats.items():
        print(f"  {cat:25s} {info['count']:6d}  ({info['percentage']}%)")

    ambiguous = sum(1 for t in tickets if t["is_ambiguous"])
    unique = len(set(t["text"] for t in tickets))
    print(f"\nAmbiguous: {ambiguous:,} ({ambiguous/len(tickets)*100:.1f}%)")
    print(f"Unique texts: {unique:,} / {len(tickets):,} ({unique/len(tickets)*100:.1f}%)")

    # Save
    output_dir = DATA_DIR
    with open(output_dir / "tickets.json", "w") as f:
        json.dump(tickets, f)
    size_mb = (output_dir / "tickets.json").stat().st_size / 1024 / 1024
    print(f"\nExported to tickets.json ({size_mb:.1f} MB)")

    sample = random.sample(tickets, 1000)
    with open(output_dir / "tickets_sample.json", "w") as f:
        json.dump(sample, f, indent=2)

    with open(output_dir / "category_stats.json", "w") as f:
        json.dump(stats, f, indent=2)

    print("Done!")


if __name__ == "__main__":
    main()
